### ISSUE TITLE
The BEST and simplest UI

### ISSUE THREAD

**Issue by tcsaddul** [lxuinet/LX.Test#3]
So far, LXUI is the BEST and simplest to learn UI framework todate for developing cross platform apps. I have three (3) issues though:

1) How soon is support for iOS?
2) Licensing Fee: Free, Donation, Commercial?
3) Support for built-in or 3rd-party MAUI controls i.e. https://github.com/dotnet/Microsoft.Maui.Graphics.Controls

**Comment by lxuinet** [comment]
Hi! I am very glad that you liked this library, I will try to answer the questions:
1. iOS, since Xamarin and SDL2 fully support the iOS platform, there is only one problem left, to test LXUI on this platform, unfortunately there is no iOS or Mac device available, but I am sure that test devices will appear in the near future.
2. The license is free zlib, in the future it is possible, commercial (or donations) with additional support, but it will rather be already LX 2.0.
3. So far there are no third-party libraries, and controls, since the library has just been published, I hope everything will appear with the help of the community of society.

I posted on CodeProject 2 articles to become, one was for some reason deleted 3 days after publication, but part 3 is already ready, looking ahead you can download the project from GitHub (https://github.com/lxuinet/LX.LayoutTest). I warn you if Visual Studio will issue package recovery errors by timeout, please unload UNO projects, they are very heavy.

**Comment by tcsaddul** [comment]
Awesome! I think many WinForms developers will seriously consider LXUI since it is the closest. What I like about this UI is its simplicity to use. It doesnt force you the XAML / MVVM junks - just pure C# coding.
